import { ShopItem as ItemType } from "@/types";
import dummyItem from "../images/dummy-item.png";
import tomato from "../images/tomato.png";

export const dummyItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
      newPrice: 1000.0,
      amountSaved: 1000,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 5,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 6,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 7,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
   {
      id: 8,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
      newPrice: 100.0,
      amountSaved: 100,
   },
];

export const recommendedItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];

export const recentItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange-american",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];

export const wishlistItems: ItemType[] = [
   {
      id: 222,
      image: tomato,
      no_of_items: 1,
      name: "Tomato",
      status: "In Stock",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 223,
      image: tomato,
      no_of_items: 1,
      name: "Tomato",
      status: "In Stock",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 224,
      image: tomato,
      no_of_items: 1,
      name: "Tomato",
      status: "In Stock",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];
