import { ShopItem as ItemType } from "@/types";
import dummyItem from "../images/dummy-item.png";

export const dummyItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 5,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 6,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 7,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 8,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];

export const recommendedItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];

export const recentItems: ItemType[] = [
   {
      id: 1,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 2000.0,
   },
   {
      id: 2,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 3,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
   {
      id: 4,
      image: dummyItem,
      no_of_items: 1,
      name: "Orange (200g)",
      rating: 4.5,
      reviews: 12,
      price: 200.0,
   },
];
